version: 2
updates:
- package-ecosystem: gomod
  directory: "/shared"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/service/holidays"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
