version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_paths = ["github.com/usk81/ashihara/shared", "github.com/usk81/ashihara/service/holidays"]
  import_root = "github.com/usk81/ashihara/"
