name-template: 'services/holidays/v$RESOLVED_VERSION'
tag-template: 'services/holidays/v$RESOLVED_VERSION'
categories:
  - title: 'new features'
    labels:
      - 'enhancement'
  - title: 'bug fixes'
    labels:
      - 'bug'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
include-labels:
  - 'service:holidays'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES
